_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "TwoStagePseudoLabGeneralizedRCNN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  RPN:
    POSITIVE_FRACTION: 0.25
    LOSS: "CrossEntropy"
  ROI_HEADS:
    NAME: "StandardROIHeadsPseudoLab"
    LOSS: "FocalLoss"
SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  STEPS: (179990, 179995)
  MAX_ITER: 180000
  IMG_PER_BATCH_LABEL: 8
  IMG_PER_BATCH_UNLABEL: 8
  BASE_LR: 0.01
  AMP:
    ENABLED: True
DATALOADER:
  SUP_PERCENT: 1.0
  RANDOM_DATA_SEED: 1
DATASETS:
  CROSS_DATASET: False
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SEMISUPNET:
  Trainer: "ubteacher"
  BBOX_THRESHOLD: 0.7
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 180000
  EMA_KEEP_RATE: 0.9996
  UNSUP_LOSS_WEIGHT: 4.0
  SUPERVISED_CROSS_LEVEL: False
  PSEUDO_LABEL_CROSS_LEVEL: False
CONSISTENCY:
  ROI_LEVEL: True
  APPLY_CLS: True
  APPLY_REG: False
  PAD_TYPE: ramp-to-proposal # ratio or min_proposal or ramnp-to-ratio
  MIN_PROPOSAL: 256
  RAMP_END: 5000
  CLS: KL
  REG: SmoothL1
  START: 2000
  END: 180000

WEIGHT_SCHEDULE:
  T1: 180000
  T2: 280000
  W1: 0.3
  W2: 0.1
  REWEIGHT: True
TEST:
  EVAL_PERIOD: 3000
  EVALUATOR: "COCOeval"